# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180510_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='month',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
