# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180510_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
