# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_myuser_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='spark934', max_length=10),
        ),
    ]
