# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180708_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='unique_id',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='userid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
