# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180709_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
