# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180717_2237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='AUser',
        ),
    ]
