# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180719_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='userid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
